/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.Test;

import com.mckay.classes.ClassOne;


import static org.junit.Assert.*;

public class AppTest {
    @Test public void appHasAGreeting() {
        ClassOne classUnderTest = new ClassOne();
        assertNotNull("app should have a greeting", classUnderTest.Name);
    }
}
